### ISSUE TITLE
Compatibility to v6.2.

### ISSUE THREAD

**Issue by kreidewe** [tollwerk/TYPO3-ext-squeezr#1]
Hi Joschi,

now we have a reminder for 6.2. compat.

Best
Sebastian

**Comment by jkphl** [comment]
@kreidewe I know it's been a long time and I'm not sure if it's still of interest, but as of now ([release v1.5.0](https://github.com/tollwerk/TYPO3-ext-squeezr/releases/tag/v1.5.0)) there's support for TYPO3 7+ in composer mode.
